Author's Name - Kalahe Wattage Sithumi Sandeera
Author's UoW - w2052090
Author's IIT No - 20220780

Name of the person who reviewed this Notebook = Thanuri Nikeshala Dodampe

In [1]:
#installing pandas
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Code Reuse Session 1 - Code block 1

In [2]:
#Python library to load and access the dataset
import pandas as pd

Code Reuse Session 1 - Code block 2

In [3]:
#loading the dataset file
data_frame=pd.read_csv('/content/5DATA002W.2 Coursework Dataset(25012025v6.0) (4).csv')

Code Reuse Session 1 - Code block 3

In [4]:
#display the recorded data values per variable
data_frame.head(10)

,Patient_ID,Month_of_Birth,Age,Sex,Occupation,T_Stage,N_Stage,6th_Stage,Differentiated,Grade,A_Stage,Tumor_Size,Estrogen_Status,Progesterone_Status,Regional_Node_Examined,Reginol_Node_Positive,Survival_Months,Mortality_Status
0,A0012,12,68.0,Female,Teaching,T1,N1,IIA,Poorly differentiated,3,Regional,4.0,Positive,Positive,24.0,1,60,Alive
1,A0013,12,50.0,Female,Medical,T2,N2,IIIA,Moderately differentiated,2,Regional,35.0,Positive,Positive,14.0,5,62,Alive
2,A0014,11,58.0,Female,Engineering,T3,N3,IIIC,Moderately differentiated,2,Regional,63.0,Positive,Positive,14.0,7,75,Alive
3,A0015,3,58.0,Female,Technology,T1,N1,IIA,Poorly differentiated,3,Regional,18.0,Positive,Positive,2.0,1,84,Alive
4,A0016,1,47.0,Female,Multimedia,T2,N1,IIB,Poorly differentiated,3,Regional,41.0,Positive,Positive,3.0,1,50,Alive
5,A0017,2,51.0,Female,Research,T1,N1,IIA,Moderately differentiated,2,Regional,20.0,Positive,Positive,18.0,2,89,Alive
6,A0018,5,51.0,Female,House Person,T1,N1,IIA,Well differentiated,1,Regional,8.0,Positive,Positive,11.0,1,54,Alive
7,A0019,4,40.0,Female,Reporting,T2,N1,IIB,Moderately differentiated,2,Regional,30.0,Positive,Positive,9.0,1,14,Dead
8,A0020,6,40.0,Female,Development,T4,N3,IIIC,Poorly differentiated,3,Regional,103.0,Positive,Positive,20.0,18,70,Alive
9,A0021,4,69.0,Female,Construction,T4,N3,IIIC,Well differentiated,1,Distant,32.0,Positive,Positive,21.0,12,92,Alive

Code Reuse Session 1 - Code block 4

In [5]:
#display the variables names
list(data_frame.columns)

['Patient_ID',
 'Month_of_Birth',
 'Age',
 'Sex',
 'Occupation',
 'T_Stage',
 'N_Stage',
 '6th_Stage',
 'Differentiated',
 'Grade',
 'A_Stage',
 'Tumor_Size',
 'Estrogen_Status',
 'Progesterone_Status',
 'Regional_Node_Examined',
 'Reginol_Node_Positive',
 'Survival_Months',
 'Mortality_Status']

Code Reuse Session 1 - Code block 5

In [6]:
#explore the data types for all the variables
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Patient_ID              4024 non-null   object
 1   Month_of_Birth          4024 non-null   int64
 2   Age                     4015 non-null   float64
 3   Sex                     4020 non-null   object
 4   Occupation              43 non-null     object
 5   T_Stage                 4024 non-null   object
 6   N_Stage                 4024 non-null   object
 7   6th_Stage               4024 non-null   object
 8   Differentiated          4024 non-null   object
 9   Grade                   4024 non-null   int64
 10  A_Stage                 4024 non-null   object
 11  Tumor_Size              4021 non-null   float64
 12  Estrogen_Status         4024 non-null   object
 13  Progesterone_Status     4024 non-null   object
 14  Regional_Node_Examined  4023 non-null   float64
 15  Reginol_Node_Positive   4024 non-null   int64
 16  Survival_Months         4024 non-null   int64
 17  Mortality_Status        4024 non-null   object
dtypes: float64(3), int64(4), object(11)
memory usage: 566.0+ KB

Code Reuse Session 1 - Code block 6

In [7]:
#display the number of instances and features
data_frame.shape

(4024, 18)

Code Reuse Session 1 - Code block 7

In [8]:
#displaying the basic descriptive statistics for the numeric variables
data_frame.describe()

,Month_of_Birth,Age,Grade,Tumor_Size,Regional_Node_Examined,Reginol_Node_Positive,Survival_Months
count,4024.000000,4015.000000,4024.000000,4021.000000,4023.000000,4024.000000,4024.000000
mean,6.481362,54.107098,2.150596,30.419299,14.373602,4.158052,71.472167
std,3.475442,11.715528,0.638234,21.161080,8.129293,5.109331,25.361855
min,1.000000,-50.000000,1.000000,-75.000000,1.000000,1.000000,1.000000
25%,3.000000,47.000000,2.000000,16.000000,9.000000,1.000000,56.000000
50%,6.000000,54.000000,2.000000,25.000000,14.000000,2.000000,73.000000
75%,10.000000,61.000000,3.000000,38.000000,19.000000,5.000000,90.000000
max,12.000000,502.000000,4.000000,140.000000,61.000000,46.000000,760.000000

Code Reuse Session 1 - Code block 8

In [9]:
#displaying the basic descriptive statistics for the categorical variables
data_frame.describe(include='object')

,Patient_ID,Sex,Occupation,T_Stage,N_Stage,6th_Stage,Differentiated,A_Stage,Estrogen_Status,Progesterone_Status,Mortality_Status
count,4024,4020,43,4024,4024,4024,4024,4024,4024,4024,4024
unique,4024,2,40,4,3,5,4,2,2,2,7
top,A4035,Female,House Person,T2,N1,IIA,Moderately differentiated,Regional,Positive,Positive,Alive
freq,1,4001,2,1786,2732,1305,2351,3932,3755,3326,3399

Code Reuse Session 1 - Code block 9

In [10]:
#shows the missing values per variable
data_frame.isnull().sum()

Patient_ID                   0
Month_of_Birth               0
Age                          9
Sex                          4
Occupation                3981
T_Stage                      0
N_Stage                      0
6th_Stage                    0
Differentiated               0
Grade                        0
A_Stage                      0
Tumor_Size                   3
Estrogen_Status              0
Progesterone_Status          0
Regional_Node_Examined       1
Reginol_Node_Positive        0
Survival_Months              0
Mortality_Status             0
dtype: int64

Code Reuse Session 1 - Code block 10

In [11]:
#removing the Occupation column from the dataset
data_frame.drop('Occupation',axis=1, inplace=True)

Code Reuse Session 1 - Code block 11

In [12]:
#shows the missing values per variable (to see that Occupation column is removed)
data_frame.isnull().sum()

Patient_ID                0
Month_of_Birth            0
Age                       9
Sex                       4
T_Stage                   0
N_Stage                   0
6th_Stage                 0
Differentiated            0
Grade                     0
A_Stage                   0
Tumor_Size                3
Estrogen_Status           0
Progesterone_Status       0
Regional_Node_Examined    1
Reginol_Node_Positive     0
Survival_Months           0
Mortality_Status          0
dtype: int64

Code Reuse Session 1 - Code block 12

In [13]:
#displaying the unique values for variable Sex
data_frame['Sex'].unique()

array(['Female', '1', nan], dtype=object)

Tutorial 1 - Code block 13

In [14]:
#percentage of missing data values
data_frame.isna().sum()/len(data_frame)*100

Patient_ID                0.000000
Month_of_Birth            0.000000
Age                       0.223658
Sex                       0.099404
T_Stage                   0.000000
N_Stage                   0.000000
6th_Stage                 0.000000
Differentiated            0.000000
Grade                     0.000000
A_Stage                   0.000000
Tumor_Size                0.074553
Estrogen_Status           0.000000
Progesterone_Status       0.000000
Regional_Node_Examined    0.024851
Reginol_Node_Positive     0.000000
Survival_Months           0.000000
Mortality_Status          0.000000
dtype: float64

Code Reuse Session 1 - Code block 15

In [15]:
#removing all the rows with missing data
data_frame = data_frame.dropna()

Code Reuse Session 1 - Code block 16

In [16]:
#shows the missing values per variable (to see that all rows with missing values are removed)
data_frame.isnull().sum()

Patient_ID                0
Month_of_Birth            0
Age                       0
Sex                       0
T_Stage                   0
N_Stage                   0
6th_Stage                 0
Differentiated            0
Grade                     0
A_Stage                   0
Tumor_Size                0
Estrogen_Status           0
Progesterone_Status       0
Regional_Node_Examined    0
Reginol_Node_Positive     0
Survival_Months           0
Mortality_Status          0
dtype: int64

Code Reuse Session 1 - Code block 17

In [17]:
#removing the Patient_ID column from the dataset as it's an unnessary column
data_frame.drop('Patient_ID',axis=1, inplace=True)

Code Reuse Session 1 - Code block 18

In [18]:
#shows the missing values per variable
data_frame.isnull().sum()

Month_of_Birth            0
Age                       0
Sex                       0
T_Stage                   0
N_Stage                   0
6th_Stage                 0
Differentiated            0
Grade                     0
A_Stage                   0
Tumor_Size                0
Estrogen_Status           0
Progesterone_Status       0
Regional_Node_Examined    0
Reginol_Node_Positive     0
Survival_Months           0
Mortality_Status          0
dtype: int64

Code Reuse Session 1 - Code block 19

In [19]:
#Python package to visualise the variables
import plotly.express as px

Code Reuse Session 1 - Code block 20

In [20]:
#visualisation method to show the frequency distribution of age
VariableName_fig = px.histogram(data_frame, x="Age")
#show the graph
VariableName_fig.show()

Code Reuse Session 1 - Code block 21

In [21]:
#visualisation method to show the frequency distribution of age
VariableName_fig = px.box(data_frame, x="Age")
#show the graph
VariableName_fig.show()

Code Reuse Session 1 - Code block 22

In [22]:
#function to detect outliers in any variable based on the interquartile range
def find_outliers_IQR(data):
  q1=data.quantile(0.25)
  q3=data.quantile(0.75)
  IQR=q3-q1
  outliers = data[((data<(q1-1.5*IQR))|(data> (q3+1.5*IQR)))]
  return outliers

Code Reuse Session 1 - Code block 23

In [23]:
#controlling rows to be displayed maximum 500
pd.set_option('display.max_rows', 500)
#controlling columns to be displayed maximum 500
pd.set_option('display.max_columns', 500)
#controlling width to be displayed maximum 150
pd.set_option('display.width', 150)

Code Reuse Session 1 - Code block 24

In [24]:
#To detect inconsistent data observations calling find_outliers_IQR function
outliers = find_outliers_IQR(data_frame['Age'])
#display the number of outliers
print("number of outliers: "+ str(len(outliers)))
#to show the indexed that have the outliers
outliers

number of outliers: 4

142    180.0
212    -50.0
522    502.0
842     89.0
Name: Age, dtype: float64

Code Reuse Session 1 - Code block 25

In [25]:
#removing the 212 row (outlier)
data_frame.drop(212, inplace = True)
#removing the 142 row (outlier)
data_frame.drop(142, inplace = True)
#removing the  row (outlier)
data_frame.drop(522, inplace = True)
#removing the 212 row (outlier)
data_frame.drop(842, inplace = True)

Code Reuse Session 1 - Code block 26

In [26]:
#visualisation method to show the frequency distribution of age
VariableName_fig = px.box(data_frame, x="Age")
#show the graph
VariableName_fig.show()

Code Reuse Session 1 - Code block 27

In [27]:
#visualisation method to show the frequency distribution of Tumor_Size
VariableName_fig = px.box(data_frame, x="Tumor_Size")
#show the graph
VariableName_fig.show()

Code Reuse Session 1 - Code block 27

In [28]:
#To detect inconsistent data observations calling find_outliers_IQR function
outliers = find_outliers_IQR(data_frame['Tumor_Size'])
#display the number of outliers
print("number of outliers: "+ str(len(outliers)))
#to show the indexed that have the outliers
outliers

number of outliers: 217

8       103.0
53       77.0
63       75.0
86      120.0
87       80.0
116      76.0
147      72.0
155     100.0
184     100.0
194      75.0
210     -75.0
215      85.0
219      75.0
220      72.0
238     120.0
254     110.0
277     100.0
289     140.0
305     130.0
316      80.0
318     100.0
322      80.0
337      90.0
362      80.0
367     100.0
376      98.0
379      90.0
401      90.0
426      75.0
441     120.0
447      80.0
476      74.0
480     100.0
483      80.0
525     100.0
526     130.0
540      87.0
564      80.0
585      81.0
593      80.0
602      80.0
630      80.0
691     100.0
705     117.0
713      76.0
740     140.0
769      90.0
828      80.0
874     123.0
877      75.0
889     130.0
893     110.0
894     133.0
897      95.0
906     107.0
909      90.0
922      92.0
937     100.0
938     105.0
971     105.0
985     100.0
1007    140.0
1095     82.0
1122     80.0
1159     85.0
1161    100.0
1193     90.0
1196    120.0
1225    120.0
1272     74.0
1289     80.0
1316    100.0
1321     76.0
1346     80.0
1355     80.0
1369     75.0
1375     82.0
1396     80.0
1462     80.0
1473     72.0
1479    120.0
1512    140.0
1522     80.0
1531     95.0
1540     90.0
1623    100.0
1668     80.0
1682    120.0
1685     90.0
1716     75.0
1739     90.0
1785     78.0
1799     97.0
1812     88.0
1870     85.0
1879     90.0
1881    100.0
1887     74.0
1915     80.0
1955     80.0
1992     80.0
2007     80.0
2028     85.0
2038     80.0
2039     90.0
2045    110.0
2055     83.0
2058     80.0
2068     80.0
2085     75.0
2094     81.0
2107     78.0
2137     85.0
2147     80.0
2157     75.0
2165     75.0
2176    110.0
2218    101.0
2223     75.0
2226     84.0
2228     90.0
2240    100.0
2249     90.0
2265     90.0
2273     90.0
2278     95.0
2283    100.0
2300     75.0
2304     92.0
2339    130.0
2340     75.0
2355     85.0
2359     83.0
2367     76.0
2380     97.0
2412     75.0
2442    115.0
2480    100.0
2484     73.0
2502     85.0
2506    120.0
2532     80.0
2563     90.0
2594     85.0
2600     80.0
2612     74.0
2623     80.0
2638     75.0
2669     75.0
2670     90.0
2672    120.0
2684     77.0
2694    125.0
2697     75.0
2700     90.0
2739    100.0
2744     85.0
2748     80.0
2759    104.0
2767    100.0
2793     75.0
2830    100.0
2872     83.0
2882     80.0
2906     80.0
2909     90.0
2910     80.0
2939     75.0
2996     78.0
3011     80.0
3014     80.0
3019     90.0
3110    100.0
3135     90.0
3190     90.0
3199     90.0
3204     72.0
3220    101.0
3231    100.0
3253     80.0
3257     80.0
3287     94.0
3309     80.0
3374     84.0
3392     74.0
3394     76.0
3399    120.0
3500     72.0
3503     90.0
3509     86.0
3554     95.0
3574     75.0
3575    100.0
3578     75.0
3582     85.0
3591    120.0
3594     90.0
3616     90.0
3620     82.0
3627     80.0
3707    100.0
3734    120.0
3754     75.0
3775    120.0
3839     80.0
3871     80.0
3888     96.0
3893     75.0
3902     80.0
3909     79.0
3910     95.0
3925     80.0
3930    120.0
3965    140.0
3991     90.0
4009    100.0
4012     80.0
Name: Tumor_Size, dtype: float64

Code Reuse Session 1 - Code block 28

In [29]:
#removing the 210 row (outlier)
data_frame.drop(210, inplace = True)
#removing the 289 row (outlier)
data_frame.drop(289, inplace = True)
#removing the 3965 row (outlier)
data_frame.drop(3965, inplace = True)
#removing the 1512 row (outlier)
data_frame.drop(1512, inplace = True)
#removing the 740 row (outlier)
data_frame.drop(740, inplace = True)
#removing the 526 row (outlier)
data_frame.drop(526, inplace = True)

Code Reuse Session 1 - Code block 29

In [30]:
#visualisation method to show the frequency distribution of Tumor_Size
VariableName_fig = px.box(data_frame, x="Tumor_Size")
#show the graph
VariableName_fig.show()

Code Reuse Session 1 - Code block 30

In [31]:
#visualisation method to show the frequency distribution of Regional_Node_Examined
VariableName_fig = px.box(data_frame, x="Regional_Node_Examined")
#show the graph
VariableName_fig.show()

Code Reuse Session 1 - Code block 31

In [32]:
##visualisation method to show the frequency distribution of Differentiated
VariableName_fig = px.histogram(data_frame, x='Differentiated')
#show the graph
VariableName_fig.show()

Code Reuse Session 1 - Code block 32

In [33]:
#finding the unique value of the column
data_frame['Month_of_Birth'].unique()

array([12, 11,  3,  1,  2,  5,  4,  6,  8,  9,  7, 10])

Code Reuse Session 1 - Code block 33

In [34]:
#finding the unique value of the column
data_frame['Age'].unique()

array([68., 50., 58., 47., 51., 40., 69., 46., 65., 48., 62., 61., 56.,
       43., 60., 57., 55., 63., 66., 53., 59., 54., 49., 64., 42., 37.,
       67., 31., 52., 33., 45., 38., 39., 36., 41., 44., 32., 34., 35.,
       30.])

Code Reuse Session 1 - Code block 34

In [35]:
#finding the unique value of the column
data_frame['Sex'].unique()

array(['Female', '1'], dtype=object)

Code Reuse Session 1 - Code block 35

In [36]:
# import a preprocessing library from Sklearn to encode ordinal columninto labels
from sklearn import preprocessing
#to encode the categorical values for
label_encoder = preprocessing.LabelEncoder()
#encoding the values
data_frame['Sex']= label_encoder.fit_transform(data_frame['Sex'])

Code Reuse Session 1 - Code block 36

In [37]:
#finding the unique value of the column
data_frame['Sex'].unique()

array([1, 0])

Code Reuse Session 1 - Code block 37

In [38]:
#finding the unique value of the column
data_frame['T_Stage'].unique()

array(['T1', 'T2', 'T3', 'T4'], dtype=object)

Code Reuse Session 1 - Code block 38

In [39]:
#to encode the categorical values for
label_encoder = preprocessing.LabelEncoder()
#encoding the values
data_frame['T_Stage']= label_encoder.fit_transform(data_frame['T_Stage'])

Code Reuse Session 1 - Code block 39

In [40]:
#finding the unique value of the column
data_frame['T_Stage'].unique()

array([0, 1, 2, 3])

Code Reuse Session 1 - Code block 40

In [41]:
#finding the unique value of the column
data_frame['N_Stage'].unique()

array(['N1', 'N2', 'N3'], dtype=object)

Code Reuse Session 1 - Code block 41

In [42]:
#to encode the categorical values for
label_encoder = preprocessing.LabelEncoder()
#encoding the values
data_frame['N_Stage']= label_encoder.fit_transform(data_frame['N_Stage'])

Code Reuse Session 1 - Code block 42

In [43]:
#finding the unique value of the column
data_frame['N_Stage'].unique()

array([0, 1, 2])

Code Reuse Session 1 - Code block 43

In [44]:
#finding the unique value of the column
data_frame['6th_Stage'].unique()

array(['IIA', 'IIIA', 'IIIC', 'IIB', 'IIIB'], dtype=object)

Code Reuse Session 1 - Code block 44

In [45]:
#to encode the categorical values for
label_encoder = preprocessing.LabelEncoder()
#encoding the values
data_frame['6th_Stage']= label_encoder.fit_transform(data_frame['6th_Stage'])

Code Reuse Session 1 - Code block 45

In [46]:
#finding the unique value of the column
data_frame['6th_Stage'].unique()

array([0, 2, 4, 1, 3])

Code Reuse Session 1 - Code block 46

In [47]:
#finding the unique value of the column
data_frame['Differentiated'].unique()

array(['Poorly differentiated', 'Moderately differentiated',
       'Well differentiated', 'Undifferentiated'], dtype=object)

Code Reuse Session 1 - Code block 47

In [48]:
#to encode the categorical values for
label_encoder = preprocessing.LabelEncoder()
#encoding the values
data_frame['Differentiated']= label_encoder.fit_transform(data_frame['Differentiated'])

Code Reuse Session 1 - Code block 48

In [49]:
#finding the unique value of the column
data_frame['Differentiated'].unique()

array([1, 0, 3, 2])

Code Reuse Session 1 - Code block 49

In [50]:
#finding the unique value of the column
data_frame['Grade'].unique()

array([3, 2, 1, 4])

Code Reuse Session 1 - Code block 50

In [51]:
#finding the unique value of the column
data_frame['A_Stage'].unique()

array(['Regional', 'Distant'], dtype=object)

Code Reuse Session 1 - Code block 51

In [52]:
#to encode the categorical values for
label_encoder = preprocessing.LabelEncoder()
#encoding the values
data_frame['A_Stage']= label_encoder.fit_transform(data_frame['A_Stage'])

Code Reuse Session 1 - Code block 52

In [53]:
#finding the unique value of the column
data_frame['A_Stage'].unique()

array([1, 0])

Code Reuse Session 1 - Code block 53

In [54]:
#finding the unique value of the column
data_frame['Tumor_Size'].unique()

array([  4.,  35.,  63.,  18.,  41.,  20.,   8.,  30., 103.,  32.,  13.,
        59.,  15.,  19.,  46.,  24.,  25.,  29.,  40.,  70.,  22.,  50.,
        17.,  21.,  10.,  27.,  23.,   5.,  51.,   9.,  55.,  77.,   2.,
        11.,  12.,  26.,  75.,  34., 120.,  80.,   3.,  60.,  14.,  16.,
        45.,  36.,  76.,  38.,  49.,   7.,  72., 100.,  43.,  62.,  37.,
        68.,  52.,  85.,  57.,  39.,  28.,  48., 110.,  65.,   6.,  42.,
       130.,  31.,  90.,  98.,  47.,  54.,  61.,  74.,  33.,   1.,  87.,
        81.,  58., 117.,  44., 123., 133.,  95., 107.,  92., 105., 140.,
        56.,  82.,  66.,  78.,  97.,  88.,  53.,  69.,  83., 101.,  84.,
       115.,  73., 125., 104.,  94.,  86.,  64.,  96.,  79.,  67.])

Code Reuse Session 1 - Code block 54

In [55]:
#finding the unique value of the column
data_frame['Estrogen_Status'].unique()

array(['Positive', 'Negative'], dtype=object)

Code Reuse Session 1 - Code block 55

In [56]:
#to encode the categorical values for
label_encoder = preprocessing.LabelEncoder()
#encoding the values
data_frame['Estrogen_Status']= label_encoder.fit_transform(data_frame['Estrogen_Status'])

Code Reuse Session 1 - Code block 56

In [57]:
#finding the unique value of the column
data_frame['Estrogen_Status'].unique()

array([1, 0])

Code Reuse Session 1 - Code block 57

In [58]:
#finding the unique value of the column
data_frame['Progesterone_Status'].unique()

array(['Positive', 'Negative'], dtype=object)

Code Reuse Session 1 - Code block 58

In [59]:
#to encode the categorical values for
label_encoder = preprocessing.LabelEncoder()
#encoding the values
data_frame['Progesterone_Status']= label_encoder.fit_transform(data_frame['Progesterone_Status'])

Code Reuse Session 1 - Code block 59

In [60]:
#finding the unique value of the column
data_frame['Progesterone_Status'].unique()

array([1, 0])

Code Reuse Session 1 - Code block 60

In [61]:
#finding the unique value of the column
data_frame['Survival_Months'].unique()

array([ 60,  62,  75,  84,  50,  89,  54,  14,  70,  92,  64,  56,  38,
        49, 105, 107,  77,  81,  78, 102,  98,  82,  86,  52,  90,  31,
        37, 103,  42,  61,  63,  39,  59,  71,  74,  73,  91, 106,  80,
        44,  85,  79,  12,  95,  55, 101,  65,  72,  57,  87,  40,  25,
         8,  53,  58,  24,  66,  69,  93,  94, 100,  96,  41,  67, 104,
        51,  13,  11,  47,  23,  45,  68,  76,  15,  16,  99,   7,  48,
        88,  34,  97, 760,  83,  17,   3,  22,  30,   6,  32,   9,   5,
        10,  19,  18,  35,  27,  36,   4,  29,  33,  26,  20,  28,  43,
         1,  46,  21,   2])

Code Reuse Session 1 - Code block 61

In [62]:
#finding the unique value of the column
data_frame['Mortality_Status'].unique()

array(['Alive', 'Dead', 'ALIVE', 'DEAD', 'ALive', 'alive', 'dead'],
      dtype=object)

Tutorial - Code block 62

In [63]:
#Making the values in Morality status lowercase
data_frame['Mortality_Status'] = data_frame['Mortality_Status'].str.lower()

Code Reuse Session 1 - Code block 63   (converting binary categorical values to numbers)

In [64]:
data_frame['Mortality_Status'] = data_frame['Mortality_Status'].map({'alive': 1 , 'dead': 2})

Code Reuse Session 1 - Code block 64

In [65]:
#finding the unique value of the column
data_frame['Mortality_Status'].unique()

array([1, 2])

Code Reuse Session 1 - Code block 65

In [66]:
#finding the unique value of the column
data_frame['Reginol_Node_Positive'].unique()

array([ 1,  5,  7,  2, 18, 12,  3, 14, 22, 17, 23,  4, 10,  6, 20, 16, 13,
       11, 24,  9,  8, 27, 21, 26, 15, 28, 19, 29, 31, 46, 33, 37, 30, 35,
       25, 32, 41, 34])

Code Reuse Session 1 - Code block 66

In [67]:
#finding the unique value of the column
data_frame['Regional_Node_Examined'].unique()

array([24., 14.,  2.,  3., 18., 11.,  9., 20., 21., 13., 23., 16.,  1.,
       22., 15.,  4., 26., 31., 25., 10.,  5.,  6., 19., 12.,  8., 17.,
       49.,  7., 33., 30., 34., 28., 32., 27., 42., 29., 39., 46., 40.,
       51., 38., 47., 54., 36., 61., 41., 60., 37., 35., 43., 52., 45.,
       57.])

Code Reuse Session 1 - Code block 67

In [68]:
#display the recorded data values per variable
data_frame.head(10)

,Month_of_Birth,Age,Sex,T_Stage,N_Stage,6th_Stage,Differentiated,Grade,A_Stage,Tumor_Size,Estrogen_Status,Progesterone_Status,Regional_Node_Examined,Reginol_Node_Positive,Survival_Months,Mortality_Status
0,12,68.0,1,0,0,0,1,3,1,4.0,1,1,24.0,1,60,1
1,12,50.0,1,1,1,2,0,2,1,35.0,1,1,14.0,5,62,1
2,11,58.0,1,2,2,4,0,2,1,63.0,1,1,14.0,7,75,1
3,3,58.0,1,0,0,0,1,3,1,18.0,1,1,2.0,1,84,1
4,1,47.0,1,1,0,1,1,3,1,41.0,1,1,3.0,1,50,1
5,2,51.0,1,0,0,0,0,2,1,20.0,1,1,18.0,2,89,1
6,5,51.0,1,0,0,0,3,1,1,8.0,1,1,11.0,1,54,1
7,4,40.0,1,1,0,1,0,2,1,30.0,1,1,9.0,1,14,2
8,6,40.0,1,3,2,4,1,3,1,103.0,1,1,20.0,18,70,1
9,4,69.0,1,3,2,4,3,1,0,32.0,1,1,21.0,12,92,1

Code Reuse Session 1 - Code block 68

In [69]:
# Export the cleaned DataFrame to a CSV file
data_frame.to_csv("cleaned_dataset.csv", index=False)

Code Reuse Session 1 - Code block 69

In [70]:
## Drop 'Survival_Months' column for classification task
classification_df = data_frame.drop(columns=['Survival_Months'])
# Save classification dataset to CSV
classification_df.to_csv("Classification_Dataset.csv", index=False)

In [71]:
# get the unique values of Morality Status
print(data_frame['Mortality_Status'].unique())

[1 2]

Code Reuse Session 1 - Code block 70

In [72]:
# Filter rows where Mortality_Status is 'Dead' for regression task
regression_df = data_frame[data_frame['Mortality_Status'] == 2]
## Drop 'Mortality_Status' column (not needed for regression)
regression_df = regression_df.drop(columns=['Mortality_Status'])
# Save regression dataset to CSV without index
regression_df.to_csv("Regression_Dataset.csv", index=False)

Code Reuse Session 1 - Code block 71

In [73]:
#displaying the size of the cleaned dataset
data_frame.shape

(3997, 16)

Code Reuse Session 1 - Code block 72

In [74]:
##visualisation method to show the frequency distribution of Mortality_Status
VariableName_fig = px.histogram(data_frame, x='Mortality_Status')
#show the graph
VariableName_fig.show()